/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Customer;
import Model.DeliveryPartner;
import Model.Product;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author fleek_kowshik
 */
public class EditJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EditJPanel
     */
    private DeliveryPartner delPackage;
    private Product productviewed;
    public EditJPanel() {
        initComponents();
    }

    EditJPanel(DeliveryPartner DeliveryPartner) {
        initComponents();
        this.delPackage = DeliveryPartner;
        
        displayPackageList();
        displayPackageDetails();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        productname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        weight = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        productid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Packageid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        productprice = new javax.swing.JTextField();
        updatejButton = new javax.swing.JButton();
        addproduct_jButton1 = new javax.swing.JButton();
        product_jComboBox1 = new javax.swing.JComboBox();
        show_jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 153));

        jLabel7.setText("Name");

        jLabel8.setText("id");

        jLabel1.setText("Package Id");

        jLabel2.setText("weight");

        jLabel3.setText("Product id");

        jLabel4.setText("product  name");

        jLabel5.setText("product price");

        updatejButton.setText("Update");
        updatejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatejButtonActionPerformed(evt);
            }
        });

        addproduct_jButton1.setText("Add Product");
        addproduct_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addproduct_jButton1ActionPerformed(evt);
            }
        });

        show_jButton1.setText("Show");
        show_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(productprice, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(productname)
                            .addComponent(productid)
                            .addComponent(Packageid)
                            .addComponent(weight, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(name)
                                    .addComponent(id, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                                .addGap(46, 46, 46))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addproduct_jButton1)
                                .addGap(56, 56, 56))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(product_jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(show_jButton1)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updatejButton)
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Packageid, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(weight, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addGap(30, 30, 30)
                .addComponent(updatejButton)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(product_jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(show_jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productid, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productprice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(addproduct_jButton1))
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updatejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatejButtonActionPerformed
        // TODO add your handling code here:
        String Id= Packageid.getText();
        String Weight= weight.getText();
//        String ProductId = productid.getText();
//        String ProductName = productname.getText();
//        String ProductPrice = productprice.getText();
        String CustomerId = id.getText();
        String CustomerName = name.getText();
        
        this.delPackage.setPackageId(Integer.valueOf(Id));
        this.delPackage.setPackageweight(Double.valueOf(Weight));
        
        Customer customer = this.delPackage.getCustomer();
        customer.setName(CustomerName);
        customer.setCustomerId(Integer.valueOf(CustomerId));
        
    }//GEN-LAST:event_updatejButtonActionPerformed

    private void addproduct_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addproduct_jButton1ActionPerformed
        // TODO add your handling code here:
        this.productviewed.setProductName(productname.getText());
        this.productviewed.setPrice(Double.valueOf(productprice.getText()));
    }//GEN-LAST:event_addproduct_jButton1ActionPerformed

    private void show_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_jButton1ActionPerformed
        // TODO add your handling code here:
        productid.setEnabled(false);
        int pid= (int)product_jComboBox1.getSelectedItem();
        
        Product prod = this.delPackage.findproduct(pid);
        this.productviewed=prod;
        
        if(!prod.equals(null)){
            productid.setText(String.valueOf(pid));
            productname.setText(prod.getProductName());
            productprice.setText(String.valueOf(prod.getPrice() ));
            
        } else{
            JOptionPane.showMessageDialog(null, "Product Not Found!");
        }
        
          
    }//GEN-LAST:event_show_jButton1ActionPerformed

    public void displayPackageList(){
        for(Product p : this.delPackage.getProduct()){
            product_jComboBox1.addItem(p.getProductId());
        }
            
    }
    
    public void displayPackageDetails(){
        
        Packageid.setText(String.valueOf(this.delPackage.getPackageId()));
        weight.setText(String.valueOf(this.delPackage.getPackageweight()));
        
        Customer customer = this.delPackage.getCustomer();
        id.setText(String.valueOf(customer.getCustomerId()));
        name.setText(customer.getName());
       
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Packageid;
    private javax.swing.JButton addproduct_jButton1;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField name;
    private javax.swing.JComboBox product_jComboBox1;
    private javax.swing.JTextField productid;
    private javax.swing.JTextField productname;
    private javax.swing.JTextField productprice;
    private javax.swing.JButton show_jButton1;
    private javax.swing.JButton updatejButton;
    private javax.swing.JTextField weight;
    // End of variables declaration//GEN-END:variables
}
